package renderer

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jppop/dmn2md/internal/model"
)

// Render converts a DMN Definitions into structured Markdown.
func Render(defs *model.Definitions) string {
	var sb strings.Builder
	writeHeader(&sb, defs)
	writeDRD(&sb, defs)
	writeDecisionsSection(&sb, defs)
	writeDataDictionary(&sb, defs)
	return sb.String()
}

func writeHeader(sb *strings.Builder, defs *model.Definitions) {
	fmt.Fprintf(sb, "# DMN Specification — %s\n\n", defs.Name)
	fmt.Fprintf(sb, "> Generated by `dmn2md`\n\n")
	fmt.Fprintf(sb, "- **Namespace** : %s\n\n", defs.Namespace)
	fmt.Fprintf(sb, "---\n\n")
}

func writeDRD(sb *strings.Builder, defs *model.Definitions) {
	fmt.Fprintf(sb, "## Decision Requirements Diagram\n\n")
	fmt.Fprintf(sb, "```mermaid\n")
	fmt.Fprintf(sb, "flowchart TD\n")

	for _, d := range defs.Decisions {
		fmt.Fprintf(sb, "  %s[\"%s\\n%s\"]\n", d.ID, d.Name, decisionType(d))
	}

	sb.WriteString("\n")
	for _, d := range defs.Decisions {
		for _, ir := range d.InformationRequirements {
			srcID := strings.TrimPrefix(ir.RequiredDecision.Href, "#")
			fmt.Fprintf(sb, "  %s --> %s\n", srcID, d.ID)
		}
	}

	fmt.Fprintf(sb, "```\n\n")
	fmt.Fprintf(sb, "---\n\n")
}

func writeDecisionsSection(sb *strings.Builder, defs *model.Definitions) {
	fmt.Fprintf(sb, "## Decisions\n\n")
	for _, d := range topoSort(defs) {
		writeDecision(sb, d, defs)
	}
}

func writeDecision(sb *strings.Builder, d model.Decision, defs *model.Definitions) {
	fmt.Fprintf(sb, "### `%s`\n\n", d.Name)
	if d.DecisionTable != nil {
		writeDecisionTableSection(sb, d, defs)
	} else if d.LiteralExpression != nil {
		writeLiteralExpressionSection(sb, d, defs)
	}
}

func writeDecisionTableSection(sb *strings.Builder, d model.Decision, defs *model.Definitions) {
	dt := d.DecisionTable
	fmt.Fprintf(sb, "- **Type** : Decision Table\n")

	if len(dt.Outputs) > 0 {
		parts := make([]string, 0, len(dt.Outputs))
		for _, o := range dt.Outputs {
			parts = append(parts, fmt.Sprintf("`%s` (`%s`)", o.Label, o.TypeRef))
		}
		fmt.Fprintf(sb, "- **outputs** : %s\n", strings.Join(parts, ", "))
	}

	if len(dt.Inputs) > 0 {
		parts := make([]string, 0, len(dt.Inputs))
		for _, inp := range dt.Inputs {
			parts = append(parts, fmt.Sprintf("`%s`", inp.InputExpression.Text))
		}
		fmt.Fprintf(sb, "- **inputs** : %s\n", strings.Join(parts, ", "))
	}

	writeDependencies(sb, d, defs)
	fmt.Fprintf(sb, "\n")

	fmt.Fprintf(sb, "#### Table\n\n")
	fmt.Fprintf(sb, "- **Hit Policy** : `%s`\n\n", dt.HitPolicy)

	// Header row
	sb.WriteString("| # |")
	for _, inp := range dt.Inputs {
		fmt.Fprintf(sb, " %s<br/>`%s` |", inp.Label, inp.InputExpression.Text)
	}
	for _, out := range dt.Outputs {
		fmt.Fprintf(sb, " %s |", out.Label)
	}
	sb.WriteString("\n")

	// Separator row
	sb.WriteString("| --- |")
	for range dt.Inputs {
		sb.WriteString(" --- |")
	}
	for range dt.Outputs {
		sb.WriteString(" --- |")
	}
	sb.WriteString("\n")

	// Data rows
	for i, rule := range dt.Rules {
		fmt.Fprintf(sb, "| %d |", i+1)
		for _, entry := range rule.InputEntries {
			text := entry.Text
			if text == "-" {
				text = "*"
			}
			fmt.Fprintf(sb, " %s |", text)
		}
		for _, entry := range rule.OutputEntries {
			fmt.Fprintf(sb, " %s |", entry.Text)
		}
		sb.WriteString("\n")
	}

	fmt.Fprintf(sb, "\n")
}

func writeLiteralExpressionSection(sb *strings.Builder, d model.Decision, defs *model.Definitions) {
	fmt.Fprintf(sb, "- **Type** : Literal Expression\n")
	writeDependencies(sb, d, defs)
	fmt.Fprintf(sb, "\n")

	fmt.Fprintf(sb, "#### Expression\n\n")
	fmt.Fprintf(sb, "```feel\n")
	fmt.Fprintf(sb, "%s\n", strings.TrimSpace(d.LiteralExpression.Text))
	fmt.Fprintf(sb, "```\n\n")
}

func writeDependencies(sb *strings.Builder, d model.Decision, defs *model.Definitions) {
	if len(d.InformationRequirements) == 0 {
		return
	}
	parts := make([]string, 0, len(d.InformationRequirements))
	for _, ir := range d.InformationRequirements {
		srcID := strings.TrimPrefix(ir.RequiredDecision.Href, "#")
		dep := findDecision(defs, srcID)
		if dep != nil {
			parts = append(parts, fmt.Sprintf("`%s`", dep.Name))
		}
	}
	if len(parts) > 0 {
		fmt.Fprintf(sb, "- **dependencies** : %s\n", strings.Join(parts, ", "))
	}
}

func writeDataDictionary(sb *strings.Builder, defs *model.Definitions) {
	type entry struct {
		Name string
		Type string
		Role string
	}

	seen := make(map[string]bool)
	var entries []entry

	for _, d := range defs.Decisions {
		if d.DecisionTable == nil {
			continue
		}
		for _, inp := range d.DecisionTable.Inputs {
			name := inp.InputExpression.Text
			if !seen[name] {
				seen[name] = true
				entries = append(entries, entry{name, inp.InputExpression.TypeRef, "Input"})
			}
		}
		for _, out := range d.DecisionTable.Outputs {
			name := out.Label
			if !seen[name] {
				seen[name] = true
				entries = append(entries, entry{name, out.TypeRef, "Output"})
			}
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	fmt.Fprintf(sb, "## Data dictionary\n\n")
	fmt.Fprintf(sb, "| Name | Type | Role | Allowed values |\n")
	fmt.Fprintf(sb, "| --- | --- | --- | --- |\n")
	for _, e := range entries {
		fmt.Fprintf(sb, "| `%s` | `%s` | %s | — |\n", e.Name, e.Type, e.Role)
	}
}

func decisionType(d model.Decision) string {
	if d.DecisionTable != nil {
		return "Decision Table"
	}
	if d.LiteralExpression != nil {
		return "Literal Expression"
	}
	return "Unknown"
}

func findDecision(defs *model.Definitions, id string) *model.Decision {
	for i := range defs.Decisions {
		if defs.Decisions[i].ID == id {
			return &defs.Decisions[i]
		}
	}
	return nil
}

// topoSort returns decisions in dependency order (leaves first).
func topoSort(defs *model.Definitions) []model.Decision {
	n := len(defs.Decisions)

	indexByID := make(map[string]int, n)
	for i, d := range defs.Decisions {
		indexByID[d.ID] = i
	}

	inDegree := make([]int, n)
	dependents := make([][]int, n)

	for i, d := range defs.Decisions {
		for _, ir := range d.InformationRequirements {
			srcID := strings.TrimPrefix(ir.RequiredDecision.Href, "#")
			srcIdx, ok := indexByID[srcID]
			if !ok {
				continue
			}
			inDegree[i]++
			dependents[srcIdx] = append(dependents[srcIdx], i)
		}
	}

	queue := make([]int, 0, n)
	for i := 0; i < n; i++ {
		if inDegree[i] == 0 {
			queue = append(queue, i)
		}
	}

	result := make([]model.Decision, 0, n)
	for len(queue) > 0 {
		idx := queue[0]
		queue = queue[1:]
		result = append(result, defs.Decisions[idx])
		for _, dep := range dependents[idx] {
			inDegree[dep]--
			if inDegree[dep] == 0 {
				queue = append(queue, dep)
			}
		}
	}

	return result
}
